// national need to run distinct from // state as getting `/tmp/` file errors (#2071)
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cdc_restricted_by_race_state.csv'
```